CREATE TABLE IF NOT EXISTS casts (
    id SERIAL PRIMARY KEY,
    movie_cast VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);